/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package combobox;

import javax.swing.JOptionPane;

/**
 *
 * @author galog
 */
public class VentanaComboBox extends javax.swing.JFrame {

    /**
     * Creates new form VentanaComboBox
     */
    public VentanaComboBox() {
        initComponents();
        
        setTitle("Agregar elementos combobox");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoPrincipal = new javax.swing.JLabel();
        TextoIntroducirDatos = new javax.swing.JTextField();
        BotonIntroducirDatos = new javax.swing.JButton();
        ComboBoxDatos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TextoPrincipal.setText("Añade el nombre de los módulos en los que estás matriculado");

        TextoIntroducirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoIntroducirDatosActionPerformed(evt);
            }
        });

        BotonIntroducirDatos.setText("Añadir");
        BotonIntroducirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIntroducirDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonIntroducirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextoIntroducirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(ComboBoxDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TextoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(TextoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoIntroducirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(BotonIntroducirDatos)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoIntroducirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoIntroducirDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoIntroducirDatosActionPerformed

    private void BotonIntroducirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIntroducirDatosActionPerformed
        //Comprobar que está vacio el campo para añadir el texto
        if (TextoIntroducirDatos.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Error, debes escribir algún elemento para poder añadirlo a la lista", getTitle(), JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Comprobar que el elemento ya está en la lista
        for (int i = 0; i < ComboBoxDatos.getItemCount(); i++) {
            if (TextoIntroducirDatos.getText().equals(ComboBoxDatos.getItemAt(i))){
                JOptionPane.showMessageDialog(rootPane, "Ya has añadido este elemento", getTitle(), JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        //Añadir al combo box lo que se escribe en el texto
        ComboBoxDatos.addItem(TextoIntroducirDatos.getText());
        //Borrar lo que se ha escrito en el texto
        TextoIntroducirDatos.setText("");
        
    }//GEN-LAST:event_BotonIntroducirDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIntroducirDatos;
    private javax.swing.JComboBox<String> ComboBoxDatos;
    private javax.swing.JTextField TextoIntroducirDatos;
    private javax.swing.JLabel TextoPrincipal;
    // End of variables declaration//GEN-END:variables
}
